- src/app/api/album/[id]/route.ts
- src/app/api/user/route.ts
- src/components/Modal/DeleteAlbumModal/DeleteAlbumModal.tsx
- src/containers/login/StyledLogin.ts
- src/hooks/useDeleteAlbum.ts
- src/services/album.ts
- src/utils/SDKUtils.ts
Feat/sharing -> main
- Feat: 공유 - 앨범 삭제 시 공유 데이터 삭제
- 앨범 삭제 기능을 api로 옮겼습니다
> Feat: 공유 - 앨범 삭제 시 공유 데이터 삭제

- src/app/api/album/[id]/sharing/route.ts
Refactor/migration -> main
예외 처리 추가
> Fix: 공유 - sharedUsers 없는 경우 예외처리

- src/app/(navRoute)/(tabBarRoute)/(albumDetail)/[uid]/[albumName]/page.tsx
- src/app/(navRoute)/(tabBarRoute)/(feed)/[uid]/[albumName]/feed/page.tsx
- src/services/album.ts
- src/services/constant.ts
- src/services/feed.ts
- src/services/model.ts
- src/services/user.ts
Refactor/migration -> main
Fix: api url 환경변수로 변경
- 상황: 배포한 웹에선 api url이 달라서 요청 실패
> Fix: api url 환경변수로 변경

- src/components/Album/Album.tsx
- src/services/feed.ts
- src/services/model.ts
Refactor/migration -> main
버그 수정
> Fix: 무한루프되지 않도록 되돌리기/SSG -> SSR

- src/services/feed.ts
- src/services/model.ts
Refactor/migration -> main
- cache: 'no-store' 없이 SSR로 동작하고 있었기 때문에, 해당 코드 제거
- 반대로 cache: 'force-cache'를 추가할 경우 SSG로 동작했음
> Style: 불필요한 코드 제거(SSR)

- src/components/AlbumItem/AlbumItem.tsx
- src/hooks/useAlbumItemLayout.ts
Feat/infiniteScroll -> main
Fix: 올바르지 않은 ref 사용 수정 / 렌더링이 완료된 후 observe하도록 코드 수정
> Fix: 올바르지 않은 ref 사용 수정

- src/app/api/feed/route.ts
- src/containers/feed/Feed.tsx
- src/utils/SDKUtils.ts
Feat/infiniteScroll -> main
- 앨범 상세, 게시물 상세 - 게시물 리스트 정렬 버그 수정
- 게시물 상세 - 스크롤 위치 버그 수정
> Fix: 앨범/게시물 상세 - 게시물 리스트 정렬 및 스크롤 위치  버그 수정

- src/app/layout.tsx
- src/components/Map/KakaoMap.tsx
- src/components/Upload/GetAccordionData.ts
- src/components/Upload/UploadModal/StyledUploadModal.ts
- src/components/Upload/UploadModal/UploadModal.tsx
Refector/upload -> main
- 변경된 스타일에 맞게 (선택) 텍스트 삭제
- 카카오 맵 연결 => 실행시 공유한 .env 파일 확인 필!
> Feat : 게시물 업로드 모달 스타일리팩토링, 카카오맵연결

- public/icons/x-white.svg
- src/components/FileUpload/Preview.tsx
- src/components/FileUpload/StyledPreview.ts
- src/components/Upload/EditModal.tsx
- src/components/Upload/UploadModal/UploadModal.tsx
- src/components/Upload/model.ts
Refector/upload -> main
업로드 게시물 코드 리팩토링 했습니다.
> Refactor/upload 업로드게시물 코드 리팩토링

- src/components/Carousel/Carousel.tsx
- src/components/Carousel/StyledCarousel.ts
Feat/feedSlider -> main
- Feat: feed - 캐러셀 스와이프 기능 추가
> :bulb: Feat: feed - 캐러셀 스와이프

- src/containers/home/Home.tsx
- src/utils/SDKUtils.ts
ex) Refactor/home -> main
1.home 컨테이너 main 에서 옮겨왔던것을 develop브랜치에서 추가로 옮겨옴
2.getAlbumList 에서 앨범삭제할때 필요한 id 값을 추가로 albumDataList 객체안에 삽입
> Fix:  홈피드 수정

- src/components/MyNonModal/StyledMyNonModal.ts
- src/components/global/GlobalStyle.ts
- src/containers/albumDetail/StyledAlbumDetail.ts
Design/global -> main
- 전역적으로 간격 조정
> Design: global 변수 변경

- src/components/Nav/Nav.tsx
- src/components/TapBar/StyledTapBar.ts
- src/components/TapBar/TapBar.tsx
- src/components/Upload/UploadModal/UploadModal.tsx
- src/containers/albumDetail/AlbumDetail.tsx
- src/hooks/useUploadFeedModalWithWebView.ts
ex) feat/login -> dev
Feat: upload - webview 통신 추가
- tapbar: a -> button
> Feat: upload - webview 통신 추가

- src/components/CommonStyled/StyledH2.ts
- src/components/Nav/StyledNav.ts
- src/containers/home/Home.tsx
- src/containers/home/StyledHome.ts
Design/sharing -> main
- 공유 UI
> Design: 공유 UI

- src/components/FileUpload/Preview.tsx
- src/components/FileUpload/StyledPreview.ts
- src/components/Map/KakaoMap.tsx
- src/components/Map/StyledKakaoMap.ts
- src/components/Upload/UploadModal/StyledUploadModal.ts
Design/upload -> main
- 게시물 업로드 모달에서 위치 검색 후 확인 버튼의 의도를 알기 어렵다 라는 피드백  => 확인 텍스트 버튼으로 수정
- 게시물 업로드시 gif 파일까지 추가 할 수 있도록 추가 
- Preview 부분 고정 사이즈 => 유동적으로 변할 수 있도록 스타일 수정
> Design: 사용자 피드백 반영한 게시물 업로드 스타일 수정

- src/components/MyNonModal/MyNonModal.tsx
- src/components/MyNonModal/model.ts
- src/containers/editProfile/EditProfile.tsx
- src/hooks/dialog/useShowNonModal.ts
Refactor/nonModal -> main
- Refactor: MyNonModal - showNonModal 훅으로 분리
> Refactor: useShowNonModal 훅 추가

- src/components/Upload/UploadModal/UploadModal.tsx
- src/containers/feed/Feed.tsx
Fix/feedDetail -> main
Fix: feed - 업로드 후 리렌더링
> Fix: feed - 업로드 후 리렌더링

- src/components/FileUpload/Preview.tsx
Dseign/upload -> main
for문을 사용하여 불러온 모든 파일의 유효성검사를 통과 하도록 수정
> :bug: Fix: 이미지 불러올 때 모든 파일의 확장자 검사하도록 수정

- src/hooks/auth/useLogin.ts
Fix/login -> main
Fix: login - 로그인 성공 시, setIsPending(false) 제거
> Fix: login - 로그인 성공 시, setIsPending(false) 제거

- src/components/MyNonModal/MyNonModal.tsx
Fix/myNonModal -> main
Fix: MyNonModal - button 클릭 후 닫히도록 수정
> Fix: MyNonModal - button 클릭 후 닫히도록 수정

- src/components/Modal/ConfirmModal/ConfirmModal.tsx
- src/components/Modal/ConfirmModal/StyledConfirmModal.ts
- src/components/Modal/DeleteFeedModal.tsx
Design/delete-feed
Design: deleteFeedModal - 해당 앨범에서만 삭제됨 text 추가
> Design: deleteFeedModal - 해당 앨범에서만 삭제됨 text 추가

- src/containers/feed/Feed.tsx
- src/modules/model.ts
- src/modules/uploadFeedModal.ts
Fix/feedDetail -> main
Fix: feed - upload 시 리렌더링 후 shouldUpdateFeedsData 상태 false로 변경
> Fix: feed - upload 시 리렌더링 후 shouldUpdateFeedsData 상태 false로 변경

- src/app/api/album/route.ts
- src/app/api/album/sharing/route.ts
- src/components/Modal/NewAlbumModal.tsx
- src/containers/home/Home.tsx
- src/containers/home/StyledHome.ts
- src/hooks/useAddAlbum.ts
- src/utils/SDKUtils.ts
ex) Refactor/home ->main
1. 홈 밑부분 여백
2. getThumbnail return값 수정
3. useState에 SSR로 받아온 홈피드 데이터값을 초깃값으로 넣어두고 앨범 추가시 albumData state에 추가 되게 구현
> Fix: 홈 피드 수정

- src/components/Modal/ArrayModal/ArrayModal.tsx
- src/components/Modal/ArrayModal/StyledArrayModal.ts
- src/containers/home/Home.tsx
- src/containers/home/StyledHome.ts
Design/arrayModal
Design: home 정렬 논모달 - 위치 디자인에 수정했습니다
> Design: home 정렬 논모달 - 위치 수정

- src/app/layout.tsx
Fix/viewport -> main
eFix: 모바일- input pocus 시,  화면이 확대되지 않도록 수정
> Fix: 모바일- input pocus 시,  화면이 확대되지 않도록 수정

- src/components/Upload/UploadModal/UploadModal.tsx
Fix/upload -> main
업로드 후 메인페이지에서 데이터 업데이트 되지 않는 부분 해결을 위해 router.refresh 추가
> :bug: Fix: 게시글 업로드 후 메인페이지에서 데이터 업데이트 되지 않는 오류 수정(#75)

- src/app/api/album/sharing/route.ts
- src/components/Album/Album.tsx
- src/components/Album/StyledAlbum.ts
- src/containers/editProfile/EditProfile.tsx
- src/containers/signup/Signup.tsx
- src/containers/signup/model.ts
- src/modules/model.ts
- src/types/album.ts
Feat/sharing -> main
- 공유 앨범 기능 추가 (자세한 내용 이슈 참고)
> Feat: 공유 앨범

- src/components/CommonStyled/StyledAuth.ts
Design/signup -> main
Design: StyledAuth - 위아래 여백 추가
> Design: StyledAuth - 위아래 여백 추가

- next.config.mjs
Refactor/upload -> main
deviceSize와 이미지 사이즈를 설정하여 이미지 랜더링 속도 개선
> :recycle: Refactor: 이미지 랜더링 속도 개선(#67)

- src/app/(navRoute)/(tabBarRoute)/(home)/page.tsx
- src/containers/login/Login.tsx
- src/containers/signup/Signup.tsx
- src/hooks/auth/useLogin.ts
- src/hooks/auth/useSingup.ts
- src/middleware.ts
Fix/login -> main
- Fix: 로그인 후 홈으로 이동하지 않는 버그 수정(자세한 내용 이슈 참고)
- Fix: / middleware - /api/album 통과하지 않도록 수정
> Fix: 로그인 후 홈으로 이동하지 않는 버그 수정 / middleware - /api/album 통과하지 않도록 수정

- src/components/EditFeed/EditFeedContents.tsx
- src/components/FileUpload/Preview.tsx
- src/components/Upload/UploadImageToStorage.tsx
- src/components/Upload/UploadModal/UploadModal.tsx
- src/components/Upload/model.ts
Co-authored-by: yonainthefish <yonaisgood@gmail.com>
Fix/upload -> main
- 기존에 이미지 선택 후 새로운 이미지를 추가하면 기존 배열에 추가 되지 않고 새로운 이미지 배열이 생겼음 => 이 부분을 개선
- 기존에 FileList로 받던 File에 대한 정보를 File[]로 수정, imageList를 받아서 newImages 에 기존 이미지 배열 imageUrl을 추가하는 형태로 해당 기능 수정
> :bug: Fix: Upload - 이미지 추가 선택이 안 되는 버그 수정(#87)

- src/components/MyNonModal/MyNonModal.tsx
- src/components/MyNonModal/StyledMyNonModal.ts
- src/containers/editProfile/EditProfile.tsx
- src/containers/my/My.tsx
- src/containers/signup/Signup.tsx
Feat/my -> main
Feat: my - 프로필 링크로 변경
> Feat: my - 프로필 링크로 변경

- src/components/FileUpload/Preview.tsx
Fix/upload => main
- 게시물 업로드시 동일한 사진 파일에 대한 유효성 검사를 매번 진행하도록 onChange 이벤트를 추가하면 매번 value 값을 빈값으로 reset해주었습니다.
> :bug: Fix: 게시물 업로드시 동일한 파일에 대해 유효성 검사 진행 되도록 기능 추가(#94)

- src/app/api/album/route.ts
- src/components/Album/StyledAlbum.ts
- src/components/Modal/NewAlbumModal.tsx
- src/utils/SDKUtils.ts
ex) Refactor/home ->main
홈 접근성 개선: 
1. 앨범 생성 모달 글자 수정 
2. 더보기 버튼 영역 확대 
Home TypeError 
getThumbnail(uid, feedId)을 실행 할때 feedId가 undefined일 경우 나는 에러였습니다.
이를 확인하고 feedId가 undefined시 getThumbnail함수를 실행하지 않고 즉시 null을 반환하는 코드를 작성하였습니다.
추가로 기존에있던 코드에서  album안에서 map을 돌며 lastFeedId 추출,getThumbnail(uid, lastFeedId)를 실행하는 코드로 변경하였습니다. 
기존Promise.all 또한 에러가날 수 있기때문에 Promise.allSettled로 변경 thumbnailPromise.status === 'fulfilled' 일경우 예외 처리를 실시했습니다.
getThumbnail 함수안에서도 docSnap && docSnap.exists() 시에만 다음작업을 수행할수있게 처리했습니다
> 🐛 홈 접근성 개선 , Home TypeError 해결

- src/components/Upload/UploadModal/UploadModal.tsx
Design/upload
Design: upload(pc, tablet) - 닫기 아이콘 white로 변경
> Design: upload(pc, tablet) - 닫기 아이콘 white로 변경

- src/containers/editProfile/StyledEditProfile.ts
- src/utils/cookie.ts
Design/editProfile -> main
- Design: edit profile - h2 간격 수정
- Fix: document 객체 존재 여부 확인
> Design: edit profile - h2 간격 수정

- src/components/Modal/InputModal/StyledInputModal.ts
- src/components/Modal/ReauthModal.tsx
- src/containers/editProfile/StyledEditProfile.ts
Design/inputModal -> main
Design: InputModal UI 깨짐 수정
> Design: InputModal UI 깨짐 수정

- src/containers/signup/Signup.tsx
- src/containers/signup/StyledSignup.ts
Refactor/signup -> main
- Refactor: signup - checkbox focus 시 outline 추가
> Refactor: signup - checkbox focus 시 outline 추가

- src/components/Accordion/StyledAccordion.ts
- src/components/Modal/SharingModal/StyledSharingModal.ts
- src/components/Topbar/HomeTopbar/StyledHomeTopbar.ts
- src/containers/home/StyledHome.ts
Design/upload
- Design: home - header 상단 고정
- Design: upload - 리디자인(간격, 이모티콘 사이즈 변동)
> Design: home - header 상단 고정/upload - 리디자인(간격, 이모티콘 사이즈 변동)

- src/app/api/feed/route.ts
Fix/Feed -> main
Fix: Feed - 게시물이 렌더링되지 않는 경우
> Fix: Feed - 게시물이 렌더링되지 않는 경우

- public/icons/loading.svg
- src/app/layout.tsx
- src/components/Album/Album.tsx
- src/components/Album/model.ts
- src/components/AlbumItem/AlbumItem.tsx
- src/components/EditFeed/EditFeedContents.tsx
- src/components/EditFeed/EditFeedModal.tsx
- src/components/FeedItem/FeedItem.tsx
- src/components/Loading/LoadingComponent.tsx
- src/components/Modal/ChangeAlbumModal/ChangeAlbumModal.tsx
- src/components/Modal/DeleteAndEditAlbumModal/DeleteAndEditAlbumModal.tsx
- src/components/Modal/DeleteFeedModal.tsx
- src/components/Modal/SharingModal/SharingModal.tsx
- src/components/Modal/SharingModal/model.ts
- src/components/MyNonModal/StyledMyNonModal.ts
- src/components/global/App.tsx
- src/containers/albumDetail/AlbumDetail.tsx
- src/containers/editProfile/EditProfile.tsx
- src/containers/editProfile/model.ts
- src/containers/feed/Feed.tsx
- src/containers/home/Home.tsx
- src/containers/my/StyledMy.ts
- src/hooks/auth/model.ts
- src/hooks/auth/useUpdateProfile.ts
- src/modules/auth.ts
- src/modules/model.ts
- src/types/user.ts
Fix/refresh
- Fix: feed/albumDetail/my/editProfile/home - 페이지 이동과 리렌더링 관련 버그 수정(자세한 내용 이슈 참고)
> Fix: 페이지 이동과 리렌더링 관련 버그 수정

- src/app/api/album/sharing/route.ts
- src/app/api/feed/route.ts
- src/components/Album/Album.tsx
- src/components/Album/model.ts
- src/containers/home/Home.tsx
- src/types/album.ts
- src/types/feed.ts
- src/utils/SDKUtils.ts
Feat/sharing -> main
- Fix: GET /album/sharing - 오타 수정(공유한 사용자가 아닌 로그인한 사용자의 프로필을 불러오던 버그)
- Feat: home - 공유 앨범 - 내가 생성한 경우 '내가 생성'
> Feat: 내가 생성 / Fix: 공유 앨범 닉네임

- src/components/Topbar/HomeTopbar/HomeTopbar.tsx
- src/components/Topbar/HomeTopbar/StyledHomeTopbar.ts
Feat/homeTopBar -> main
Feat: home - topbar logo 클릭 시 Scroll Top
>  Feat: home - topbar logo 클릭 시 Scroll Top

- src/components/Modal/ConfirmModal/ConfirmModal.tsx
- src/components/Modal/ConfirmModal/StyledConfirmModal.ts
- src/components/Modal/DeleteAndEditAlbumModal/DeleteAndEditAlbumModal.tsx
- src/components/Modal/NewAlbumModal.tsx
- src/containers/home/StyledHome.ts
Fix/home-> main
Fix: home - edit/delete/add 후 경로 이동 후 돌아오면 이전 데이터 렌더링하는 버그
> Fix: home - edit/delete/add 후 경로 이동 후 돌아오면 이전 데이터 렌더링하는 버그

- src/hooks/auth/useUpdateProfile.ts
Fix/refresh -> main
- Fix: edit 후 my/editProfile 업데이트
> Fix: edit 후 my/editProfile 업데이트

- src/app/layout.tsx
Feat/meta -> main
meta og title 오타 수정
> :lipstick: Style: 오타 수정

- src/hooks/auth/useLogin.ts
Fix/login -> main
- Fix: login - 로그인 후 홈으로 이동하지 않는 경우
> Fix: login - 로그인 후 홈으로 이동하지 않는 경우

- src/components/Modal/DeleteFeedModal.tsx
- src/components/Upload/UploadModal/StyledUploadModal.ts
Fix/upload -> main
아이폰 사파리에서 header 잘림 해결
> Design: upload - 아이폰 사파리에서 header 잘림

- src/app/(navRoute)/(tabBarRoute)/(albumDetail)/[uid]/album/page.tsx
- src/app/(navRoute)/(tabBarRoute)/(feed)/[uid]/album/feed/page.tsx
- src/hooks/useAlbumName.ts
- src/middleware.ts
Fix/albumDetail -> main
- Fix: albumDetail/feed - albumName .인 경우 예외 처리
> Fix: albumDetail/feed - albumName .인 경우 예외 처리

- src/components/FeedItem/FeedItem.tsx
Fix/Feed -> main
Fix: Feed - time 계산 오류
> Fix: Feed - time 계산 오류

- src/components/AlbumItem/AlbumItem.tsx
- src/components/AlbumItem/StyledAlbumItem.ts
- src/components/CommonStyled/a11yHidden.ts
Fix/albumDetail -> main
Refactor: albumDetail - hover 시 스타일 변경 코드 js -> css
> Refactor: albumDetail - hover 시 스타일 변경 코드 js -> css

- src/app/api/album/sharing/route.ts
- src/components/EditFeed/EditFeedContents.tsx
- src/components/Upload/UploadModal/UploadModal.tsx
- src/hooks/useAddAlbum.ts
- src/hooks/useGetSavedAlbumList.ts
- src/types/album.ts
- src/types/feed.ts
- src/utils/SDKUtils.ts
Refactor/database -> main
Refactor: Feed data 변경 및 data 타입명 변경
> Refactor: Feed data 변경 및 data 타입명 변경

- src/components/EditFeed/EditFeedContents.tsx
- src/hooks/useEditFeed.ts
- src/types/feed.ts
- src/utils/cookie.ts
Refactor/type -> main
Refactor: 인덱스 시그니처 제거
> Refactor: 인덱스 시그니처 제거

- src/components/EditFeed/EditFeedContents.tsx
- src/components/Modal/DeleteFeedModal.tsx
- src/components/Modal/SharingModal/SharingModal.tsx
- src/components/MyNonModal/MyNonModal.tsx
- src/components/Nav/Nav.tsx
- src/components/Upload/GetAccordionData.ts
- src/components/Upload/UploadModal/UploadModal.tsx
- src/containers/editProfile/EditProfile.tsx
- src/containers/privacy/Privacy.tsx
- src/containers/terms/Terms.tsx
- src/hooks/auth/useAuthState.ts
- src/hooks/useAddAlbum.ts
- src/hooks/useEditAlbum.ts
- src/hooks/useEditFeed.ts
- src/hooks/useGetSavedAlbumList.ts
- src/hooks/useUpdateFeedList.ts
Refactor/redux -> main
♻️ Refactor: auth - 사용하는 상태에만 접근하도록 수정
> ♻️ Refactor: auth - 사용하는 상태에만 접근하도록 수정

- src/modules/auth.ts
- src/modules/page.ts
- src/modules/signup.ts
- src/modules/uploadFeedModal.ts
Refactor/feed -> Develop
Fix: Reducer - 매개변수 순서
> Fix: Reducer - 매개변수 순서
